apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sfrs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-sfrs@sha256:f3fc36af2bf8a1a67aba4070af91ef13ae5cde53df62fa87d25832fe95621e3f
        name: my-nodejs
        resources: {}
status: {}
